import { type AnyPgColumn, pgTable, uuid, text, timestamp, jsonb, index, integer, bigint, boolean } from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { agents } from "./agents.js";
import { agentWakeupRequests } from "./agent_wakeup_requests.js";

export const heartbeatRuns = pgTable(
  "heartbeat_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    agentId: uuid("agent_id").notNull().references(() => agents.id),
    invocationSource: text("invocation_source").notNull().default("on_demand"),
    triggerDetail: text("trigger_detail"),
    status: text("status").notNull().default("queued"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    error: text("error"),
    wakeupRequestId: uuid("wakeup_request_id").references(() => agentWakeupRequests.id),
    exitCode: integer("exit_code"),
    signal: text("signal"),
    usageJson: jsonb("usage_json").$type<Record<string, unknown>>(),
    resultJson: jsonb("result_json").$type<Record<string, unknown>>(),
    sessionIdBefore: text("session_id_before"),
    sessionIdAfter: text("session_id_after"),
    logStore: text("log_store"),
    logRef: text("log_ref"),
    logBytes: bigint("log_bytes", { mode: "number" }),
    logSha256: text("log_sha256"),
    logCompressed: boolean("log_compressed").notNull().default(false),
    stdoutExcerpt: text("stdout_excerpt"),
    stderrExcerpt: text("stderr_excerpt"),
    errorCode: text("error_code"),
    externalRunId: text("external_run_id"),
    processPid: integer("process_pid"),
    processGroupId: integer("process_group_id"),
    processStartedAt: timestamp("process_started_at", { withTimezone: true }),
    retryOfRunId: uuid("retry_of_run_id").references((): AnyPgColumn => heartbeatRuns.id, {
      onDelete: "set null",
    }),
    processLossRetryCount: integer("process_loss_retry_count").notNull().default(0),
    scheduledRetryAt: timestamp("scheduled_retry_at", { withTimezone: true }),
    scheduledRetryAttempt: integer("scheduled_retry_attempt").notNull().default(0),
    scheduledRetryReason: text("scheduled_retry_reason"),
    issueCommentStatus: text("issue_comment_status").notNull().default("not_applicable"),
    issueCommentSatisfiedByCommentId: uuid("issue_comment_satisfied_by_comment_id"),
    issueCommentRetryQueuedAt: timestamp("issue_comment_retry_queued_at", { withTimezone: true }),
    livenessState: text("liveness_state"),
    livenessReason: text("liveness_reason"),
    continuationAttempt: integer("continuation_attempt").notNull().default(0),
    lastUsefulActionAt: timestamp("last_useful_action_at", { withTimezone: true }),
    nextAction: text("next_action"),
    contextSnapshot: jsonb("context_snapshot").$type<Record<string, unknown>>(),
    stuckScore: integer("stuck_score"),
    stuckStatus: text("stuck_status"),
    lastStuckCheckAt: timestamp("last_stuck_check_at", { withTimezone: true }),
    stuckCheckCount: integer("stuck_check_count").notNull().default(0),
    stuckWarningCommentPostedAt: timestamp("stuck_warning_comment_posted_at", { withTimezone: true }),
    stuckWarningDismissedAt: timestamp("stuck_warning_dismissed_at", { withTimezone: true }),
    stuckWarningDismissedBy: text("stuck_warning_dismissed_by"),
    // Phase 3: Auto-escalation fields
    stuckAdminReviewTaskId: uuid("stuck_admin_review_task_id"),
    stuckAdminReviewCreatedAt: timestamp("stuck_admin_review_created_at", { withTimezone: true }),
    stuckAdminReviewNotifiedAt: timestamp("stuck_admin_review_notified_at", { withTimezone: true }),
    stuckCancelledAt: timestamp("stuck_cancelled_at", { withTimezone: true }),
    stuckCancelledBy: text("stuck_cancelled_by"),
    stuckCancelReason: text("stuck_cancel_reason"),
    stuckCancellationNotifiedAt: timestamp("stuck_cancellation_notified_at", { withTimezone: true }),
    stuckGracePeriodStartedAt: timestamp("stuck_grace_period_started_at", { withTimezone: true }),
    stuckRetryOfRunId: uuid("stuck_retry_of_run_id").references((): AnyPgColumn => heartbeatRuns.id, {
      onDelete: "set null",
    }),
    stuckRetryCount: integer("stuck_retry_count").notNull().default(0),
    stuckRetryScheduledAt: timestamp("stuck_retry_scheduled_at", { withTimezone: true }),
    stuckRecoveryStatus: text("stuck_recovery_status").notNull().default("none"),
    stuckRecoveryCompletedAt: timestamp("stuck_recovery_completed_at", { withTimezone: true }),
    stuckOptOutAt: timestamp("stuck_opt_out_at", { withTimezone: true }),
    stuckOptOutBy: text("stuck_opt_out_by"),
    stuckCircuitBreakerTriggered: boolean("stuck_circuit_breaker_triggered").notNull().default(false),
    stuckCircuitBreakerReason: text("stuck_circuit_breaker_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyAgentStartedIdx: index("heartbeat_runs_company_agent_started_idx").on(
      table.companyId,
      table.agentId,
      table.startedAt,
    ),
    companyLivenessIdx: index("heartbeat_runs_company_liveness_idx").on(
      table.companyId,
      table.livenessState,
      table.createdAt,
    ),
    companyStuckIdx: index("heartbeat_runs_company_stuck_idx").on(
      table.companyId,
      table.stuckStatus,
      table.lastStuckCheckAt,
    ),
    // Phase 3: Auto-escalation indexes
    stuckAdminReviewIdx: index("heartbeat_runs_stuck_admin_review_idx").on(
      table.companyId,
      table.stuckAdminReviewTaskId,
      table.stuckAdminReviewCreatedAt,
    ),
    stuckCancelledIdx: index("heartbeat_runs_stuck_cancelled_idx").on(
      table.companyId,
      table.stuckCancelledAt,
      table.stuckRecoveryStatus,
    ),
    stuckRetryIdx: index("heartbeat_runs_stuck_retry_idx").on(
      table.companyId,
      table.stuckRetryOfRunId,
      table.stuckRetryScheduledAt,
    ),
    stuckCircuitBreakerIdx: index("heartbeat_runs_stuck_circuit_breaker_idx").on(
      table.companyId,
      table.stuckCircuitBreakerTriggered,
      table.stuckCancelledAt,
    ),
  }),
);
